---

node_1:
  hosts:
    node_1:
      ansible_host: "{{ lookup('ansible.builtin.env', 'NODE_1_ADDRESS') }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'NODE_USER') }}"
      ansible_become_password: "{{ lookup('ansible.builtin.env', 'NODE_PASS') }}"
      ansible_ssh_private_key_file: "/workdir/private_key.pem"
      ansible_python_interpreter: /usr/bin/python3
      node_name: "{{ lookup('ansible.builtin.env', 'NODE_1_NAME') }}"
      node_hostname: "{{ lookup('ansible.builtin.env', 'NODE_1_HOSTNAME') }}"
      node_address: "{{ lookup('ansible.builtin.env', 'NODE_1_ADDRESS') }}"

node_2:
  hosts:
    node_2:
      ansible_host: "{{ lookup('ansible.builtin.env', 'NODE_2_ADDRESS') }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'NODE_USER') }}"
      ansible_become_password: "{{ lookup('ansible.builtin.env', 'NODE_PASS') }}"
      ansible_ssh_private_key_file: "/workdir/private_key.pem"
      ansible_python_interpreter: /usr/bin/python3
      node_name: "{{ lookup('ansible.builtin.env', 'NODE_2_NAME') }}"
      node_hostname: "{{ lookup('ansible.builtin.env', 'NODE_2_HOSTNAME') }}"
      node_address: "{{ lookup('ansible.builtin.env', 'NODE_2_ADDRESS') }}"

node_3:
  hosts:
    node_3:
      ansible_host: "{{ lookup('ansible.builtin.env', 'NODE_3_ADDRESS') }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'NODE_USER') }}"
      ansible_become_password: "{{ lookup('ansible.builtin.env', 'NODE_PASS') }}"
      ansible_ssh_private_key_file: "/workdir/private_key.pem"
      ansible_python_interpreter: /usr/bin/python3
      node_name: "{{ lookup('ansible.builtin.env', 'NODE_3_NAME') }}"
      node_hostname: "{{ lookup('ansible.builtin.env', 'NODE_3_HOSTNAME') }}"
      node_address: "{{ lookup('ansible.builtin.env', 'NODE_3_ADDRESS') }}"

all_nodes:
  children:
    node_1:
    node_2:
    node_3:

control_panel_nodes:
  children:
    node_1:

worker_nodes:
  children:
    node_2:
    node_3:
